services:
  apache:
    build:
      context: ./apache
      args:
        APACHE_RELOAD_SECRET: ${APACHE_RELOAD_SECRET}
        SERVER: 16ram-4cpu
        PETE_ENVIRONMENT: ${PETE_ENVIRONMENT}
    restart: always
    volumes:
      - wp_data:/var/www/html           
      - apache_sites_available:/etc/apache2/sites-available
      - apache_sites_enabled:/etc/apache2/sites-enabled
      - pma_data:/usr/src/phpmyadmin:ro
      - ssl_data:/etc/letsencrypt
      - apache_logs:/var/log/apache2 
    environment:
      APACHE_RELOAD_SECRET: ${APACHE_RELOAD_SECRET}
      APACHE_RELOAD_URL: ${APACHE_RELOAD_URL}
      APACHE_CERTBOT_URL: ${APACHE_CERTBOT_URL}
      LOGROTATE_INTERVAL: 43200 
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - demo3.petelocal.net
          - demo3.wordpresspete.org
          - wordpresspete.petelocal.net
          - dashboard.wordpresspete.petelocal.net
          - mydashboard.wordpresspete.petelocal.net
          - dashboard.wordpresspete.com
          - dashboard.deploypete.petelocal.net
          - deploypete.petelocal.net
    mem_limit: 1500m
    mem_reservation: 1024m
    cpus: "1.5"
    ulimits:
      nofile:
        soft: 131072
        hard: 131072
      nproc:  8192
  php:
    build:
      context: ./php
      args:
        PETE_ENVIRONMENT: "${PETE_ENVIRONMENT}"
        PHP_VERSION: "${PHP_VERSION}"
        SERVER: 16ram-4cpu
    restart: always
    depends_on:                # ← php waits for apache, db, redis
      - apache
      - db
      - redis
    expose:
      - "9000"                           
    volumes:
      - wp_data:/var/www/html
      - ssh_data:/var/www/.ssh
      - ssh_data:/root/.ssh
      - apache_sites_available:/etc/apache2/sites-available
      - apache_sites_enabled:/etc/apache2/sites-enabled
      - pma_data:/usr/src/phpmyadmin
      - ssl_data:/etc/letsencrypt
      - apache_logs:/var/log/apache2      
    env_file: .env                       
    environment:
      WORDPRESS_DB_HOST: db:3306
      PETE_DB_NAME: ${PETE_DB_NAME}
      PETE_DB_USER: ${PETE_DB_USER}
      PETE_DB_PASSWORD: ${PETE_DB_PASS}
      PETE_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PETE_ENVIRONMENT: ${PETE_ENVIRONMENT}
      APACHE_RELOAD_SECRET: ${APACHE_RELOAD_SECRET}
      APACHE_RELOAD_URL: ${APACHE_RELOAD_URL}
      APACHE_CERTBOT_URL: ${APACHE_CERTBOT_URL}
      REDIS_HOST: redis
      PHP_VERSION: 8.2
    mem_limit: 4096m
    mem_reservation: 3072m
    cpus: "2.5"
    ulimits:
      nofile:
        soft: 131072
        hard: 131072
      nproc:  8192
  db:
    build:
      context: ./db
      args:
        SERVER: 16ram-4cpu
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    mem_limit: 8192m
    mem_reservation: 6144m
    cpus: "3.0"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc: 16384
      memlock:
        soft: -1
        hard: -1
  redis:
    image: redis:7-alpine
    restart: always
    mem_limit: 512m
    mem_reservation: 256m
    memswap_limit: 1024m
    cpus: "0.5"

volumes:
  wp_data:
  db_data:
  ssh_data:
  apache_sites_available:
  apache_sites_enabled:
  pma_data:
  ssl_data:
  apache_logs: