version: "3.8"

services:
  # 1) WordPress + PHP-Apache
  wordpress:
    build: ./wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ssh_data:/root/.ssh
      - apache_data:/etc/apache2
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      PETE_DB_NAME: ${PETE_DB_NAME}
      PETE_DB_USER: ${PETE_DB_USER}
      PETE_DB_PASSWORD: ${PETE_DB_PASS}
      PETE_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    ports:
      - "80:80"

  # 2) MariaDB
  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db-config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./db-config/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  # 3) Redis for object caching
  redis:
    image: redis:7-alpine
    restart: always

volumes:
  wp_data:
  db_data:
  ssh_data:
  apache_data: